### ISSUE TITLE
[Request] color_data.pt and grayscale_data.pt files from train_vae.py?

### ISSUE THREAD

**Issue by EagleVee** [timoklein/car_racer#1]
Hi,
I've just cloned your project, and I want to try to train the weights.pt and VAE_weights.pt again, but can't seem to find the 2 files color_data.pt and grayscale_data.pt from the internet. Can you share those files to me?
Sorry if this is a stupid question. I'm really new at Machine learning.
Thank you very much!

```
if __name__ == '__main__':
    # get data
    path_to_x = "/home/jupyter/tutorials/praktikum_ml/color_data.pt"
    path_to_y = "/home/jupyter/tutorials/praktikum_ml/grayscale_data.pt"
    train_loader, valid_loader = get_data(path_to_x, path_to_y)

    # instantiate model and optimizer
    vae = ConvBetaVAE()
    vae.to(DEVICE)

    train_model(20)

    # save model
    vae.cpu()
    torch.save(vae.state_dict(), 'weights.pt')
```

**Comment by timoklein** [comment]
Hey, sorry for the late reply.
The files `color_data.pt` and `grayscale_data.pt` aren't uploaded because they are too large to upload on GitHub.
You can generate these yourself however with the following steps:
1. Generate a dataset of training images using the `generate_AE_data.py`. The images will be stored in large numpy arrays.
2. Convert the training data into torch tensors using the functions *convert_to_tensor* and *convert_to_grayscale* from `utils.py`.

Having done this, you can either concatenate both image tensors into a single tensor if you have a lot of ram or you implement your own torch dataset class to train the VAE. Hope it helps :)
